from datetime import timedelta
import pandas as pd
import yfinance as yf

# Load JSON from file generated by chatGPT from email
df = pd.read_json('earning-report.json')
df['earning date'] = pd.to_datetime(df['earning date'])
df['option expiry date'] = pd.to_datetime(df['option expiry date'])

# Define a function to get date_before_earning based on market time
def get_date_before_earning(earning_date, market_time):
    return earning_date if market_time.lower() == "after market" else earning_date - timedelta(days=1)

# Add date_before_earning column
df['date_before_earning'] = df.apply(lambda row: get_date_before_earning(row['earning date'], row['before/after market']), axis=1)

# Define a function to fetch historical close prices around the earnings date and option expiry
def get_stock_data(ticker, date_before_earning, earning_date, option_expiry_date):
    stock = yf.Ticker(ticker)
    hist = stock.history(start=date_before_earning - timedelta(days=1), end=option_expiry_date + timedelta(days=1))
    hist.index = hist.index.normalize().tz_localize(None)

    last_close_before_earning = hist.loc[date_before_earning]['Close'] if date_before_earning in hist.index else None
    close_after_earning = hist.loc[earning_date]['Close'] if earning_date in hist.index else None
    close_on_expiry = hist.loc[option_expiry_date]['Close'] if option_expiry_date in hist.index else None
    return last_close_before_earning, close_after_earning, close_on_expiry

# Populate the additional columns
df[['last_close_before_earning', 'close_after_earning', 'close_on_expiry']] = df.apply(
    lambda row: get_stock_data(row['symbol'], row['date_before_earning'], row['earning date'], row['option expiry date']), axis=1, result_type='expand'
)

# Define the function to calculate profit/loss (P/L) based on option expiry date
def calculate_pl(row):
    stock_buy_price = row['stock buy price']
    option_price = row['option price']
    close_on_expiry = row['close_on_expiry']
    option_strike_price = row['option strike price']

    if close_on_expiry is None:
        return None  # If there's no price data on the expiry date, we cannot calculate P/L

    # Initial investment for buying 100 shares
    initial_investment = stock_buy_price * 100

    # Premium collected from selling one call option
    option_premium = option_price * 100

    # Calculate the stock sale price on the option expiry date with the option in mind
    if close_on_expiry >= option_strike_price:
        sale_price = option_strike_price * 100  # Sell at strike price due to call option
    else:
        sale_price = close_on_expiry * 100  # Sell at market price on expiry date

    # Final P/L calculation
    profit_loss = sale_price + option_premium - initial_investment
    return profit_loss

# Apply the function to add a new column 'profit_loss'
df['profit_loss'] = df.apply(calculate_pl, axis=1)

# Display the modified DataFrame with the new 'profit_loss' column
print(df[['name', 'symbol', 'close_on_expiry', 'profit_loss']])